name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 1.0.1+1
homepage: https://github.com/mattreid1/firebase_image

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  sqflite: ^2.2.0+3
  idb_sqflite: ^1.1.1
  path: ^1.8.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
