name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 1.0.1+1
homepage: https://github.com/mattreid1/firebase_image

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
  sqflite: ^2.0.0+2
  idb_sqflite: ^1.0.0
  path: ^1.8.0
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
